<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath/>
    </parent>

    <groupId>com.mok.framework</groupId>
    <artifactId>mok-framework</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>mok-framework</name>
    <description>mok-framework</description>

    <modules>
        <module>mok-framework-app</module>
        <module>mok-framework-common</module>
        <module>mok-framework-auth</module>
        <module>mok-framework-captcha</module>
        <module>mok-framework-test</module>
        <module>mok-framework-operationLog</module>
        <module>mok-framework-monitor</module>
        <module>mok-framework-mq</module>
        <module>mok-framework-model</module>
        <module>mok-framework-task</module>
        <module>mok-framework-base</module>
        <module>mok-framework-file</module>
        <module>mok-framework-excel</module>
        <module>mok-framework-ai</module>
        <module>mok-framework-mail</module>
    </modules>

    <properties>
        <java.version>17</java.version>

        <!-- 数据库 -->
        <mysql.version>8.0.33</mysql.version>
        <mybatis-plus.version>3.5.7</mybatis-plus.version>

        <!-- 消息队列 -->
        <spring-rabbit.version>3.1.1</spring-rabbit.version>

        <!-- 工具类 -->
        <hutool.version>5.8.42</hutool.version>
        <fastjson2.version>2.0.60</fastjson2.version>

        <!-- 文档 -->
        <springdoc.version>2.8.6</springdoc.version>

        <!-- slf4j -->
        <slf4j.version>2.0.17</slf4j.version>

        <!-- swagger -->
        <swagger.version>2.2.29</swagger.version>

        <!-- springdoc -->
        <springdoc.version>2.8.6</springdoc.version>

        <!-- elasticsearch -->
        <elasticsearch.version>3.5.9</elasticsearch.version>

        <!-- jakarta.mail. -->
        <jakarta.mail.version>2.0.2</jakarta.mail.version>

        <!-- commons-io -->
        <commons-io.version>2.16.1</commons-io.version>

        <!-- commons-lang3 -->
        <commons-lang3.version>3.17.0</commons-lang3.version>

        <!-- 动态数据源版本 -->
        <dynamic-datasource.version>4.3.1</dynamic-datasource.version>

        <!-- FESOD - apache电子表格 -->
        <fesod-sheet.version>2.0.1-incubating</fesod-sheet.version>

        <!-- okhttp -->
        <okhttp.version>4.12.0</okhttp.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- MyBatis Plus (Spring Boot 3 适配) -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!-- MySQL Connector -->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
                <scope>runtime</scope>
            </dependency>

            <!-- RabbitMQ 客户端（若需单独使用） -->
            <dependency>
                <groupId>org.springframework.amqp</groupId>
                <artifactId>spring-rabbit</artifactId>
                <version>${spring-rabbit.version}</version>
            </dependency>


            <!-- Hutool -->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <!-- Fastjson2 -->
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <!-- SpringDoc OpenAPI -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>

            <!-- 管理 SLF4J API 版本 -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version> <!-- 版本请根据实际情况调整 -->
            </dependency>

            <!-- Swagger Annotations -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger.version}</version>
            </dependency>

            <!-- elasticsearch -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>


            <!-- 工具类 -->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
            </dependency>

            <!-- commons-io -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <!-- 动态数据源 -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
                <version>${dynamic-datasource.version}</version>
            </dependency>

            <!-- FESOD - apache电子表格 -->
            <dependency>
                <groupId>org.apache.fesod</groupId>
                <artifactId>fesod-sheet</artifactId>
                <version>${fesod-sheet.version}</version>
            </dependency>

            <!-- OkHttp 用于调用大模型API -->
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>1.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>